### ISSUE TITLE
BeforeSplit and Aftersplit mixed up?

### ISSUE THREAD

**Issue by nobleBean** [karlwancl/YahooFinanceApi#40]
Could there be the possibility that BeforeSplit and AfterSplit are mixed up?

**Comment by dshe** [comment]
Could you please let me know the security symbol, date and split ratio?

**Comment by nobleBean** [comment]
For Example APPL on June 09, 2014 1/7 Stock Split. Doesn´t this mean that you got for one stock 7 stocks after the split? Or do I read it wrong?

**Comment by cshawky** [comment]
investor.apple.com: "Apple's stock has split four times since the company went public. The stock split on a 7-for-1 basis on June 9, 2014 and split on a 2-for-1 basis on February 28, 2005, June 21, 2000, and June 16, 1987."
So on that basis I would divide price by 7. i.e. 1/7
