### ISSUE TITLE
Only works with Flurl Http 2.1.0 and Flurl 2.5.2

### ISSUE THREAD

**Issue by axelarati** [karlwancl/YahooFinanceApi#41]
When I install the newest version of flurl (2.4.2 flurl.http and 2.8.2 flurl), there is an exception in Yahoo.QueryAsync() where it says that it cannot find the assembly Flurl.Http 2.1.0.

**Comment by dshe** [comment]
I suggest you try:

https://github.com/dshe/YahooQuotesApi
