### ISSUE TITLE
stock split before after data is always zero

### ISSUE THREAD

**Issue by libu1129** [karlwancl/YahooFinanceApi#50]
symbol = DOV

**Comment by libu1129** [comment]
solution

internal static SplitTick ToSplitTick(string[] row)

var split = row[1].Split('/');
=>
var split = row[1].Split(':');

**Comment by dshe** [comment]
I suggest you try: https://github.com/dshe/YahooQuotesApi

**Comment by Ricky-G** [comment]
@dshe does your api support stock splits and company buyouts etc?

**Comment by dshe** [comment]
dividends and splits are supported
