### ISSUE TITLE
v7 API now breaks with "code":"Unauthorized","description":"Invalid Cookie"

### ISSUE THREAD

**Issue by kamoco** [karlwancl/YahooFinanceApi#54]
Can you please convert it to v6. V6 works.

**Comment by emoreau99** [comment]
I have the same issue. What do you mean by "convert it to v6"?

**Comment by emoreau99** [comment]
never mind. Found it (at least I think). You meant to change the URL to use V6 instead of V7

**Comment by reviloxx** [comment]
I cloned the project and added optional parameters to select the api version. It works fine with v6 as suggested by @kamoco. However, I don't have permissions to push my branch and create a PR.

**Comment by kamoco** [comment]
sorry for the late reply. Yes change the url to v6. I could not create a new package that worked otherwise I would have shared that.

**Comment by softwarefactory1** [comment]
Hi anyone that can create dll and share it? Thanks

**Comment by softwarefactory1** [comment]
> [YahooFinanceApi.zip](https://github.com/karlwancl/YahooFinanceApi/files/11463099/YahooFinanceApi.zip)
> 
> It uses v6 as default and you also have an optional parameter to select a different version in all public methods which do a request. Just in case the working version changes again.

Thanks now i have this error:
Method not found: 'Void CsvHelper.CsvReader..ctor(System.IO.TextReader, System.Globalization.CultureInfo)'.

**Comment by kamoco** [comment]
Looks like v6 is not working now. Is it working for you guys? I am getting 
{"finance":{"result":null,"error":{"code":"Not Found","description":"HTTP 404 Not Found"}}}

**Comment by emoreau99** [comment]
same year, v6 stopped working. Any solution/workaround?

**Comment by emoreau99** [comment]
might explain! 
![image](https://github.com/karlwancl/YahooFinanceApi/assets/6817203/7260b664-2dc9-4655-9188-66191f5ba8d5)

**Comment by sergemat** [comment]
Just FYI. I got it working with v7 using [this workaround](https://stackoverflow.com/questions/76065035/yahoo-finance-v7-api-now-requiring-cookies-python).

I also updated all nuget packages to most recent version to keep this code somewhat current. Unfortunately, that broke Flurl cookies handling and SVC parsing, so I had to fix those as well.

I will fork this repo and create PR shortly.

**Comment by karlwancl** [comment]
Hi @sergemat 
Thanks for your contribution on this project. I'm no longer using Yahoo finance anymore and this project has been unmaintained for a while. 

If you really wish to help and do the update, I can give you the collaborator role so you could help to update it accordingly. Are you okay with that?

**Comment by sergemat** [comment]
Hi @karlwancl. Yes, please do. I'm still using it :).

**Comment by karlwancl** [comment]
@sergemat invited, have fun :)

**Comment by sergemat** [comment]
@karlwancl the deployment fails due to outdated nuget API Key. I don't have access to the repo settings to assign a new one. Please update the key.

**Comment by karlwancl** [comment]
@sergemat I have updated the key and re-run the build. The new nuget package should be up now, please try to see if it works. Thanks.
